# Generated by Django 3.0.4 on 2020-03-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers'),
    ]

    operations = [
    ]
